# Generated by Django 3.1.1 on 2020-09-15 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedField1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedField2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedField3_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedField3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relfield3_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.relatedfield3_2')),
            ],
        ),
        migrations.CreateModel(
            name='MainTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.IntegerField()),
                ('field2', models.IntegerField()),
                ('field3', models.IntegerField()),
                ('field4', models.DecimalField(decimal_places=1, max_digits=10)),
                ('field5', models.IntegerField(null=True)),
                ('field6', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('relfield1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.relatedfield1')),
                ('relfield2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.relatedfield2')),
                ('relfield3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.relatedfield3')),
            ],
        ),
    ]
